### ISSUE TITLE
Package Download Fails on Windows (w/o Run as Administrator)

### ISSUE THREAD

**Issue by Shrinks99** [coldtype/st2#1]
The "Download & Install Coldtype" button seems to fail with the following error:

```shell
Python: Traceback (most recent call last):
  File "C:\Users\Henry\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Coldtype\__init__.py", line 658, in execute
    importer.install_coldtype(context, globals())
  File "C:\Users\Henry\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Coldtype\importer.py", line 31, in install_coldtype
    run([sys.executable, "-m", "pip", "install", *args], check=1, env=environ_copy)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\bin\\python.EXE', '-m', 'pip', 'install', 'coldtype[blender]']' returned non-zero exit status 1.
```
After running Blender in Python debug mode and trying the command again I was able to get this error message:

```shell
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\Lib\\site-packages\\six.py'
Consider using the `--user` option or check the permissions.
```

Running Blender as admin seems to fix this permissions error and allows the package to be installed.  I don't think running the command as `--user` will work because I think the Program Files directory requires authentication?  Either way, seems to be a permissions problem.

Tested on Windows 11, I suspect the same problem will arise on Windows 10.

**Comment by stenson** [comment]
Thanks for reporting that! I totally forgot I had to do the same thing on Windows 10 to get it to work (run as admin) — did try to figure out a way around it (which is what the `environ_copy` reference is about in the code (note to self)), though came up empty. Will keep this open until we can either figure out if it's truly impossible with administrator privileges or if there is a good workaround.

Don't think you'll need to run as admin for future sessions tho, fwiw.

**Comment by stenson** [comment]
Have now deprecated Download & Install Coldtype (as it is bundled) as of 0.9 — might be some problems w/ the new setup of course, but should avoid any administrator issues
