### ISSUE TITLE
Question: Kerning Individual Pairs?

### ISSUE THREAD

**Issue by EricKramp** [coldtype/st2#12]
Thanks for the rad plugin @stenson! 

I haven't been able to figure out if it's possible to manually kern individual letter pairings though, I see the effects of turning on/off the kern feature, but as you can see in my screenshot a little extra attention is warranted if possible.

![image](https://user-images.githubusercontent.com/1298131/200040755-d25cc3aa-4d3b-45d6-9dd0-3f46e67d776c.png)

**Comment by stenson** [comment]
hi @EricKramp — interesting suggestion! Do you have the native Blender alt-arrow kerning feature in mind?

Coldtype-python (the library that ST2 depends on) has a "kern_pairs" feature that lets you specify letter pair kerns in the format `{"A/B":10}` — a pair separated by a slash and then a single numeric value (i.e. how kerning is specified in font editing apps). That number is in "font units" (so it's unrelated to the units in Blender itself), but maybe that'd be pretty close to what you have in mind?

A pretty obscure addition to the ST2 UI, but very powerful for specific use-cases — here's an example where the "KP" (kern-pairs) are set to `{"D/I":-15, "R/I": 10, "N/G":-30}`

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/89770/200088043-92187d1d-3104-4d87-ab99-96738beb4d2e.png">

This is currently up on main, but I'll include it with the next release if that seems like a good feature. Unfortunately it'd be difficult/impossible to implement something like alt+arrow letter-spacing feature of Blender's native text tool.

**Comment by EricKramp** [comment]
@stenson thanks for the quick reply! I'd be stoked have access to your existing "kern_pairs" feature.

In terms of a Blender specific interaction, I'm pretty out of practice with Blender and it's changed a lot in the last few years, so I'm not sure what the best native interaction would be tbh. I found your plugin just looking for a UI based way to experiment with variable type animation.

I'll give it a think though and let you know if I come up with anything.

**Comment by stenson** [comment]
just uploaded a new version (https://github.com/coldtype/st2/releases/tag/v0.8) if you want to try out the kerning pairs feature — it should look and work exactly like that screenshot above (in the Font Features sub-panel)

**Comment by EricKramp** [comment]
Thanks, it does work with new text objects but doesn't seem to take affect with text objects created before the plugin update.

Not a problem for my current experiment, but just FYI
