### ISSUE TITLE
Not showing up/installing in Blender 3.4

### ISSUE THREAD

**Issue by benkiel** [coldtype/st2#13]
Seems like something is amiss with ST2 and Blender 3.4, as I can't get it to show up/install

**Comment by stenson** [comment]
Hi Ben! Just tried out 3.4 on my computer for the first time & ST2 seemed to work correctly, although I already had it installed so maybe it was able to skip some error specific to 3.4.

If you're able to start Blender from the command line ([like this](https://docs.blender.org/manual/en/2.79/render/workflows/command_line.html#macos)), could you try installing ST2 again and see if any error messages are printed out?

**Comment by benkiel** [comment]
I am an idiot. I _may_ have downloaded the source code zip and not the package zip and tried to install that....

Works just fine if you download the correct thing, who would have thought?

**Comment by stenson** [comment]
glad to hear it's working! have to admit i've done the same with other blender addons!
