### ISSUE TITLE
Newline enhancement on Windows

### ISSUE THREAD

**Issue by jayliu50** [coldtype/st2#18]
First, thank you so much for your work. I consider this plugin _essential_ for motion typography on Blender.

Little request to enhance the newline feature. Entering newlines and changing the position of newlines happens a lot especially when I'm wordsmithing or typesetting. Right now on Windows, I'm basically copying and pasting a lot. I cut the text that is intended to go after a newline, hit the newline button (because it always appends), and then paste the text in. Yes, it's minor, but since it happens so much, I thought I'd write this request.

Some Ideas for your consideration

1. When pressing the newline button, could the plugin insert the newline at the cursor within the field, rather than at the end
2. Have the plugin intercept SHIFT+ENTER when the user is focused on the field and enter a paragraph symbol for the user
3. Use another character like pipe `|` or something that can be typed easily by all platforms. Perhaps it could be something the user can configure.

Not sure how feasible any of the options would be, but I think that could go a long way (especially here on Windows without the hotkey). 

I realize that using the text-block is a great feature, but there are times when it's just a two-deck text, and it's nice to just have the text all there without having to look into another panel. But maybe there is yet another way that I'm not aware of, which I'd be curious to know.

Thanks for your consideration of this request and for your work!

**Comment by stenson** [comment]
Thanks for the request! That all makes sense. I don't think 1 or 2 are possible given the limitations of Blender Python API (though they would be great solutions), but I think I can make something happen with 3 — hopefully soon. I'll update this issue when I get a chance to work on it.

**Comment by stenson** [comment]
Hi @jayliu50 — sorry for the delay here. Does this build work for you? https://coldtype.xyz/st2/downloads/ST2-v0-11_win.zip The interface now includes a text box where you can configure which character to use as the newline delimiter

**Comment by jayliu50** [comment]
Yes, that works for me! Thank you so much!!
