### ISSUE TITLE
Issue with Google Fonts: Certain Font Styles Trigger q2c Conversion Error

### ISSUE THREAD

**Issue by ocmc3142** [coldtype/st2#24]
First, thank you for developing such an excellent addon!

I am encountering an issue with certain Google Fonts where specific font styles do not render and give the error message provided below. Notably, this issue typically does not occur with shorter text strings (e.g., "Text"), but it sometimes arises when using longer text (e.g., "The quick brown fox jumps over the lazy dog.").

From my observations, it appears that the **q2c** conversion function is failing for some font styles. I am unsure whether this is related to the naming conventions of these styles, specific glyphs, or the **q2c** function itself.

**Examples:**
* Nunito: The variable font versions work perfectly, but the following static styles (Light, Regular, Semibold) generate the error quoted below.
* Quicksand: The variable font version fails to render, with only the Light weight from the static directory functions properly.
* Open Sans: Both the variable fonts and all static styles render without issue. There are no issues with this font.

**Key Findings:**
* In many cases, the italic variant renders correctly while the corresponding regular (upright) version triggers the error.
* While the issue arises usually for longer text, I found that for some problematic styles the error arises even with shorter text (e.g., "Text.", with a period after Text). However, this only occurs with certain problematic styles, not across the board.

**System Specifications:**
* ST2 version: 0.15
* Blender version: 4.2.1
* Operating System: Windows 11

**Error Traceback:**
> Traceback (most recent call last):
>   File "...\Blender\4.2\scripts\addons\ST2\properties.py", line 115, in <lambda>
>     font_path: bpy.props.StringProperty(name="Font", default="", update=lambda p, c: update_type_and_copy("font_path", p, c))
>                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "...\Blender\4.2\scripts\addons\ST2\properties.py", line 19, in update_type_and_copy
>     active = _update_type(props, context)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "...\Blender\4.2\scripts\addons\ST2\properties.py", line 11, in _update_type
>     t.update_live_text_obj(t.two_dimensional())
>   File "...\Blender\4.2\scripts\addons\ST2\typesetter.py", line 385, in update_live_text_obj
>     to.draw(p, set_origin=False, fill=False)
>   File "...\Blender\4.2\scripts\addons\ST2\inline-packages\coldtype\blender\fluent.py", line 933, in draw
>     path = path.q2c()
>            ^^^^^^^^^^
>   File "...\Blender\4.2\scripts\addons\ST2\inline-packages\coldtype\runon\path.py", line 2616, in q2c
>     qp0 = Point(new_vl[-1][-1][-1])
>                 ~~~~~~~~~~~~~~^^^^
> IndexError: tuple index out of range
> File "...\Blender\4.2\scripts\addons\ST2\properties.py", line 115, in <lambda>

I hope this information helps in identifying the root cause. Please let me know if you need any further details or testing from my side.

**Comment by stenson** [comment]
Thanks for filing this issue! I've been able to repro it locally, and it looks like it's an issue with a library we use (skia-pathops) that's returning some path instructions that don't quite make sense (to me at least). I'll be trying to figure it out, hopefully will have a solution soon!

**Comment by stenson** [comment]
Does this updated version of ST2 work for you? https://coldtype.xyz/st2/releases/ST2-v0-16_blender41_win.zip

It turns out the issue is related to a special kind of quadratic curve notation in certain TTF fonts, and hopefully this new build avoids that style of notation when building the curves.

**Comment by ocmc3142** [comment]
Thank you for your quick response and fix. Based on my tests so far, everything is looking great! I really appreciate the timely resolution and the effort you put into maintaining this excellent piece of software.

**Comment by ocmc3142** [comment]
Thank you for your quick response and fix. Based on my tests so far, everything is looking great! I really appreciate the timely resolution and the effort you put into maintaining this excellent piece of software.

**Comment by stenson** [comment]
cool! thanks for filing that bug!
