### ISSUE TITLE
Can't initialize Coldtype for Blender v0.5, `AttributeError: module 'Coldtype.importer' has no attribute 'C'`

### ISSUE THREAD

**Issue by Shrinks99** [coldtype/st2#7]
Installing the new version of Coldtype for Blender into Blender 3.3 on Windows 11 results in this error:

```txt
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Henry\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Coldtype\__init__.py", line 25, in <module>
    if importer.C is not None:
AttributeError: module 'Coldtype.importer' has no attribute 'C'
```

I suspect this is due to migrating my settings from 3.2 to 3.3.  I previously had v0.4 of the plugin installed with Blender 3.2.  After deleting the coldtype folder from `Blender 3.3\3.3\python\lib\site-packages` the addon loads and seems to work as expected (though of course I have to download and install Coldtype again which makes sense).

**Comment by stenson** [comment]
Ah thanks for reporting, not quite sure why this is happening, but most likely has to do with 0.5 of coldtype-blender requiring a newer version of coldtype-python (0.9.10) — will investigate to see if I can reproduce this locally

**Comment by Shrinks99** [comment]
Is there a reason (I'm sure there is) for not shipping coldtype-python with the addon?  I only ask because this setup seems to be responsible for both bug reports I've filed :P

Also unrelated but the new text entry features are great!  This plugin has pretty much already replaced Blender's stock text entry for me, I greatly appreciate its existence and look forward to actually using it in my work in the near future hopefully... :D

**Comment by stenson** [comment]
Great to hear the text entry features are working well!

As for including coldtype — that is certainly something we could do, since the coldtype-python source code is fully cross-platform — that said, the main reason to not include it is that it'd be impossible to include all of coldtype's other dependencies in the addon source (such as ones that ship native c-libraries that pip installs), and coldtype-python lists all those dependencies in a neat bundle

**Comment by stenson** [comment]
Just wanted to say thanks for suggesting the bundle-python idea — took a little doing (and now there are separate zips for windows and the two mac archs as of 0.9 on coldtype.xyz/st2) but definitely an improvement over the downloading-with-blender-pip
